#! /bin/bash

# To make optimal use of this script, configure a cron job as follows:
#	1. Edit crontab using "crontab -e"
#	2. Add this line "30 20 * * * cd <path_to_script> && <path_to_script>/theScript"
#	3. Schedule this for a time when you computer will be on... the above line is 8:30 pm, every day

#-----------------------------------------------------------------------------------------------------------#

# Write the date + time of the commit to the log file
date >> log.txt

# Commit and push to remote
	# Bash does not like quotes in commands, 
	# so we save commands as a variables and evaluate instead of just executing
COMMAND1='git commit -a -m "Todays commit"'
COMMAND2='git push'
eval $COMMAND1
eval $COMMAND2

